application: push-sms
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: .*
  script: pushsms.app


libraries:
- name: jinja2
  version: latest